# Generated by Django 2.2.17 on 2021-02-10 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=70)),
                ('tz', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='JobDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=50)),
                ('total_exp', models.IntegerField(default=0)),
                ('skills', models.CharField(max_length=200)),
                ('job_desc', models.CharField(max_length=200)),
                ('image_url', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employeeinfo.User')),
            ],
        ),
    ]
