# Generated by Django 2.2.17 on 2021-02-10 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeeinfo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobdetails',
            name='location',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='jobdetails',
            name='role',
            field=models.CharField(max_length=100),
        ),
    ]
