# Generated by Django 2.2.17 on 2021-02-11 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeeinfo', '0002_auto_20210210_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.AutoField(db_column='id', primary_key=True, serialize=False),
        ),
    ]
